### ISSUE TITLE
GCMS-Davidson-Felix - "documentation"

### ISSUE THREAD

**Issue by davidsonfe** [davidsonfe/GCMS-Davidson-Felix#1]
[README](https://github.com/davidsonfe/GCMS-Davidson-Felix/blob/main/README.md)

@ramidedantas

**Comment by ramidedantas** [comment]
@davidsonfe você criou um novo repositório não foi isso? Não precisava mas ok.

Ajuste o Readme desse repositório para ficar como no formato do meu repositório, depois eu adiciono meu nome.

Corrija o seu link acima, tirando o espaço entre o fecha-colchete ] e abre-parenteses (.

**Comment by ramidedantas** [comment]
@davidsonfe Readme ok, pode fechar.
